services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - '6379:6379'
    mem_limit: 10M
    networks:
      - app-network

  app:
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    env_file:
      - .env
    environment:
      GOOGLE_KEY_FILE: /home/ubuntu/whisprr_backend/gcp-credentials.json
    depends_on:
      - redis
    command: yarn run start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
