export enum PurchaseStatus {
  SUBSCRIPTION_RECOVERED = 'SUBSCRIPTION_RECOVERED', // 정기 결제가 계정 보류에서 복구되었습니다.
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED', // 활성 정기 결제가 갱신되었습니다.
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED', // 정기 결제가 취소되었습니다.
  SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED', // 새로운 정기 결제가 구매되었습니다.
  SUBSCRIPTION_ON_HOLD = 'SUBSCRIPTION_ON_HOLD', // 정기 결제가 계정 보류 상태가 되었습니다.
  SUBSCRIPTION_IN_GRACE_PERIOD = 'SUBSCRIPTION_IN_GRACE_PERIOD', // 정기 결제가 유예 기간 상태로 전환되었습니다.
  SUBSCRIPTION_RESTARTED = 'SUBSCRIPTION_RESTARTED', // 정기 결제가 복원되었습니다.
  SUBSCRIPTION_PRICE_CHANGE_CONFIRMED = 'SUBSCRIPTION_PRICE_CHANGE_CONFIRMED', // 정기 결제 가격 변경이 확인되었습니다.
  SUBSCRIPTION_DEFERRED = 'SUBSCRIPTION_DEFERRED', // 정기 결제 갱신 기한이 연장되었습니다.
  SUBSCRIPTION_PAUSED = 'SUBSCRIPTION_PAUSED', // 정기 결제가 일시중지되었습니다.
  SUBSCRIPTION_PAUSE_SCHEDULE_CHANGED = 'SUBSCRIPTION_PAUSE_SCHEDULE_CHANGED', // 정기 결제 일시중지 일정이 변경되었습니다.
  SUBSCRIPTION_REVOKED = 'SUBSCRIPTION_REVOKED', // 정기 결제가 만료 시간 전에 취소되었습니다.
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED', // 정기 결제가 만료되었습니다.
  SUBSCRIPTION_PENDING_PURCHASE_CANCELED = 'SUBSCRIPTION_PENDING_PURCHASE_CANCELED', // 대기 중인 거래의 정기 결제가 취소되었습니다.
}
